### ISSUE TITLE
鏈接一直失敗

### ISSUE THREAD

**Issue by fai2002** [toomore/grs#16]
我使用pycharm+django+python2.7
在使用grs模塊的時候一直出現此錯誤：HTTPConnectionPool(host='mis.tse.com.tw', port=None): Max retries exceeded with url: /stock/api/getStockInfo.jsp?ex_ch=otc_070279.tw_20141118&json=1&delay=0&_=1416282457 (Caused by ProtocolError('Connection aborted.', error(10060, '')))
我不知道什麼原因，應該怎麼解決？

**Comment by earxx** [comment]
不好意思 ,現在才看到這篇文,大陸確實 有封鎖 mis.twse.com.tw ,  設 proxy 就可以解了, 我以前都是這樣做,但現在是 API 改版,所以 光解網路問題是沒用的
