### ISSUE TITLE
有關一些建議

### ISSUE THREAD

**Issue by wenhuay** [toomore/grs#19]
1.cvs資料檔停留在2013/12/18，可否要更新，或建立自動上網更新機制
2.TWSENo().industry_code.keys()與TWSENo().industry_comps.keys()兩者資料不盡相同，可否更改一下！
3.有些股票如果抓太多資料(24月) stock('xxxx',24)，無法讀取
4.遇到剛剛下市的股票，會出現錯誤，，無法讀取
　ex:<2015.2.4>代號：2384 --> AttributeError: 'Stock' object has no attribute 　'_SimpleAnalytics__raw_data'

感謝你！你的程式很好用。

**Comment by toomore** [comment]
@wenhuay 收到了！感謝你，我找時間再來修正 XD

**Comment by wenhuay** [comment]
對了！還有一點建議。補充資料一定要以『月』為單位嗎？可否以『日』來追加？就看database缺哪幾天，往後補上去。這樣也讓TWSE、OTC官網的loading不會太重。(尤其是OTC，真的非常慢！)
真是感謝你呀！

**Comment by wenhuay** [comment]
這兩天(過年之後)，OTC的資料無法抓取。後來看了http://grs.toomore.net/，也是一樣OTC的資料都無法看到。是否OTC他們的網址更改了呢？

**Comment by toomore** [comment]
@wenhuay OTC 連結問題修正了 https://github.com/toomore/grs/releases/tag/v0.6.2

**Comment by wenhuay** [comment]
非常的感恩！

**Comment by wenhuay** [comment]
你的demo網站都關了！沒有想再打開嗎？還是有人很喜歡耶！

**Comment by toomore** [comment]
@wenhuay 啊啊啊啊，不好意思，主機重開機沒注意到這沒開啟，好感謝你的支持！！！！

**Comment by wenhuay** [comment]
謝謝你的處理。還有goristock可不可以也打開呢？感恩！
