### ISSUE TITLE
plus_mons 壞掉了>___<

### ISSUE THREAD

**Issue by Asoul** [toomore/grs#20]
> stock = Stock("2618')
> stock.plus_mons(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/grs/fetch_data.py", line 121, in plus_mons
    oldraw = list(self.__raw_data)
AttributeError: 'Stock' object has no attribute '_FetchData__raw_data'

**Comment by Asoul** [comment]
所以我現在只好用二分搜來爬月份 QQ

**Comment by toomore** [comment]
= =a 我瞭解一下，感謝你的回報！

**Comment by jack482653** [comment]
TWSEFetch和OTCFetch沒有初始化父類別 所以找不到_FetchData__raw_data
另外serial_fetch和plus_mons也沒有把result存進_FetchData__raw_data
我修改之後就可以work了
