### ISSUE TITLE
有關csv資料來源

### ISSUE THREAD

**Issue by weihautin** [toomore/grs#23]
作者你好
有關twse_list.csv
證期會代碼,公司簡稱,分類代碼,分類名稱
UPDATE,2013/12/18,x,x
1312,國喬,03,塑膠工業

關於分類代碼,分類名稱你是去哪邊找的？
整個csv是你自己整理的嗎？

**Comment by toomore** [comment]
@weihautin Hi, 可以參考這裡[1]，中間右邊有個下拉選單「	分類項目：」，我是參考那裡的編號與分類名稱 ;)

[1] http://www.twse.com.tw/ch/trading/exchange/MI_INDEX/MI_INDEX.php

**Comment by weihautin** [comment]
謝謝作者,我主要想知道csv檔案是手動整理還是用程式整理?
如果是手動整理,我可能未來有機會寫一個程式來抓取,並分享. 
如果股票csv檔是用程式抓取彙整可否分享?

**Comment by toomore** [comment]
@weihautin 酷！感謝你！
