### ISSUE TITLE
RealtimeTWSE 出現錯誤

### ISSUE THREAD

**Issue by jackzzjack** [toomore/grs#29]
可以問一下這部分的錯誤訊息嗎 ??

    >>> from grs import RealtimeTWSE
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: cannot import name RealtimeTWSE

謝謝

**Comment by toomore** [comment]
@jackzzjack 操作沒有問題，可能要看看當前 path 是否錯誤。
