### ISSUE TITLE
最近上市股票資料抓不到！上櫃都沒問題。

### ISSUE THREAD

**Issue by wenhuay** [toomore/grs#33]
最近上市股票資料抓不到！上櫃都沒問題。

**Comment by ianleu** [comment]
應該是網站的擷取資料格式改版了
url='http://www.twse.com.tw/ch/trading/exchange/STOCK_DAY/STOCK_DAYMAIN.php?'
payload={'download':'csv','CO_ID':'2330','query_year':'2016'i,'query_month':'8'}
res_data=requests.post(url,data=payload,stream=True)
這樣就可以抓到2016年8月的資料了，可是不知道怎樣修改現有模組

**Comment by sshorse731** [comment]
使用下列patch更新/usr/local/lib/python2.7/dist-packages/grs/fetch_data.py

--- fetch_data.py.old   2016-09-10 21:52:54.612261268 +0800
+++ fetch_data.py       2016-09-10 21:59:55.450694143 +0800
@@ -31,6 +31,7 @@
 from cStringIO import StringIO
 from datetime import datetime
 from dateutil.relativedelta import relativedelta
+import requests

 TWSE_HOST = 'http://www.twse.com.tw/'
 TWSE_CONNECTIONS = urllib3.connection_from_url(TWSE_HOST)
@@ -194,17 +195,11 @@
             :param datetime nowdatetime: 此刻時間
             :rtype: list
         """
-        url = (
-            '/ch/trading/exchange/' +
-            'STOCK_DAY/STOCK_DAY_print.php?genpage=genpage/' +
-            'Report%(year)d%(mon)02d/%(year)d%(mon)02d_F3_1_8_%(stock)s.php' +
-            '&type=csv&r=%(rand)s') % {'year': nowdatetime.year,
-                                       'mon': nowdatetime.month,
-                                       'stock': stock_no,
-                                       'rand': random.randrange(1, 1000000)}
+       url='http://www.twse.com.tw/ch/trading/exchange/STOCK_DAY/STOCK_DAYMAIN.php?'
+       payload={'download':'csv','CO_ID':stock_no,'query_year':nowdatetime.year,'query_month':nowdatetime.month}
+       res_data=requests.post(url,data=payload,stream=True)
         logging.info(url)
-        result = TWSE_CONNECTIONS.urlopen('GET', url)
-        csv_files = csv.reader(StringIO(result.data))
+        csv_files = csv.reader(StringIO(res_data.content))
         self.__url.append(TWSE_HOST + url)
         return csv_files

**Comment by sshorse731** [comment]
使用附件更新/usr/local/lib/python2.7/dist-packages/grs/fetch_data.py
[fix_failed_to_get_twse_data.patch.txt](https://github.com/toomore/grs/files/465449/fix_failed_to_get_twse_data.patch.txt)

**Comment by toomore** [comment]
@wenhuay @ianleu @sshorse731 已修正更新到 v0.7.0

@sshorse731 感謝提供修正，但 `grs` 內部不使用 `requests`，直接只用 `urllib3`
