### ISSUE TITLE
判斷台灣股市是否開市民國年與西元年日期會有不同的結果

### ISSUE THREAD

**Issue by Hung-Jia-Jun** [toomore/grs#43]
我輸入
open_or_not.d_day(datetime(2017, 02, 06)) #西元年 2017/02/06是否開市
True 
顯示為有開市

但當我輸入
open_or_not.d_day(datetime(106, 02, 06))#民國年
False
顯示為未開市
原始資料內容 
2454聯發科
 [u'106/02/06', 10439845.0, 2200855430.0, 208.0, 214.0, 206.0, 212.0, u'+5.00', 5853.0, u'']
有這個天的資料的

**Comment by toomore** [comment]
python 的 `datetime` 一律都是西元年，可能搞混了。所以輸入 `106` 對 python datetime 是 西元 106 年。
