### ISSUE TITLE
即時盤的資訊無法取得

### ISSUE THREAD

**Issue by shih928** [toomore/grs#44]
從 GITHUB 下載了 grs 0.7.0, 執行起來一切都好唯獨無法取得即時盤的股價資訊. 查閱了歷史資料, 以前似乎也曾發生過類似的問題 (如 issue #39 擷取華研即時股價出現錯誤)

不知即時盤的資訊是只在 2016/11 月底的時候無法取得呢? 抑或是從此以後再也無法取得了呢?
請問這是因為台灣證劵交易所不提供即時的資訊嗎?
煩請不吝告知, 謝謝!

**Comment by toomore** [comment]
@shih928 感謝你

由於證交所的 基本市況報導網站[1]，現在會偵測 IP，如果同一時間密集查詢會被擋掉，所以這功能沒有辦法正常運作。

我在另外一個語言的版本有嘗試修正[2]，但是目前也無法解決，所以暫時都無法使用。

[1] http://mis.twse.com.tw/
[2] https://github.com/toomore/gogrs/compare/pr-1

**Comment by shih928** [comment]
Thanks for your prompt response and the status update!
Hopefully you can conquer this technical gap soon, looking forward to hearing the good news from you.  ^^
